# backend/services/gemini.py
from typing import Dict, Any, Optional
from google import genai
from google.genai import types
from ..core.logging import logger
from ..core.config import settings

class GeminiService:
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.GEMINI_API_KEY
        if self.api_key:
            self.client = genai.Client(api_key=self.api_key)
            self.model = "gemini-3.5-flash"
        else:
            self.client = None
            self.model = "gemini-3.5-flash"
        logger.info("GeminiService initialized", extra={"payload": {"model": self.model}})

    async def generate_response(
        self, 
        prompt: str, 
        system_prompt: Optional[str] = None,
        response_schema: Optional[Any] = None
    ) -> str:
        """
        Sends requests to Gemini API for various tasks.
        Uses the new google.genai SDK.
        """
        if not self.client:
            logger.warning("Gemini API key not configured. Returning mock response.")
            return self._get_mock_response(prompt, system_prompt)

        logger.info(
            "Sending payload request to Gemini model service",
            extra={
                "payload": {"prompt_length": len(prompt), "model": self.model}
            }
        )

        try:
            # Build the full prompt with system prompt if provided
            full_prompt = prompt
            if system_prompt:
                full_prompt = f"{system_prompt}\n\n{prompt}"

            # Generate content
            response = await self.client.aio.models.generate_content(
                model=self.model,
                contents=full_prompt
            )
            return response.text
        except Exception as e:
            logger.error(f"Gemini API call failed: {str(e)}")
            return f"Error: {str(e)}"

    async def generate_structured_response(
        self,
        prompt: str,
        response_schema: Any,
        system_prompt: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generates structured output using Gemini's structured outputs feature.
        Uses Pydantic models for type-safe responses.
        """
        if not self.client:
            logger.warning("Gemini API key not configured. Returning mock structured response.")
            return self._get_mock_structured_response(response_schema)

        try:
            full_prompt = prompt
            if system_prompt:
                full_prompt = f"{system_prompt}\n\n{prompt}"

            response = await self.client.aio.models.generate_content(
                model=self.model,
                contents=full_prompt,
                config=types.GenerateContentConfig(
                    response_schema=response_schema,
                    response_mime_type="application/json"
                )
            )
            return response.text
        except Exception as e:
            logger.error(f"Gemini structured output generation failed: {str(e)}")
            return self._get_mock_structured_response(response_schema)

    def _get_mock_response(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        """Returns mock response when API key is not configured."""
        return f"""[MOCK RESPONSE - Gemini API not configured]

System: {system_prompt or 'You are a helpful assistant.'}

User: {prompt[:100]}...

Response: This is a mock response demonstrating the expected output format.
In production, this would be generated by Gemini AI with the actual prompt.

To enable real responses, set the GEMINI_API_KEY environment variable."""

    def _get_mock_structured_response(self, response_schema: Any) -> Dict[str, Any]:
        """Returns mock structured response when API key is not configured."""
        # Return a mock structure based on the schema type
        if hasattr(response_schema, 'model_json_schema'):
            # Pydantic model
            return {
                "mock_data": True,
                "note": "This is a mock response. Set GEMINI_API_KEY for real data.",
                "schema_type": response_schema.__name__
            }
        return {"mock_data": True, "note": "This is a mock response. Set GEMINI_API_KEY for real data."}


# Global instance
gemini_service = GeminiService()