# backend/services/openrouter_service.py
"""OpenRouter service for AI fallback when Gemini fails or hits rate limits."""

from typing import Optional, Dict, Any
from openrouter import OpenRouter
import os
try:
    from core.config import settings
    from core.logging import logger
except ImportError:
    from backend.core.config import settings
    from backend.core.logging import logger


class OpenRouterService:
    """Service for calling OpenRouter API as backup for Gemini."""
    
    def __init__(self):
        self.api_key = getattr(settings, 'OPENROUTER_API_KEY', None) or os.getenv('OPENROUTER_API_KEY')
        self.available = bool(self.api_key)
        self.default_model = "openrouter/owl-alpha"  # Use owl-alpha as per user instruction
        self.fallback_models = [
            "openrouter/owl-alpha",
            "meta-llama/llama-3.2-3b-instruct:free",
            "microsoft/phi-3-mini-128k-instruct:free"
        ]
        
        if self.available:
            logger.info("OpenRouter service initialized", extra={"payload": {"model": self.default_model}})
        else:
            logger.warning("OpenRouter API key not configured")
    
    async def generate_response(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model: Optional[str] = None
    ) -> Optional[str]:
        """
        Generate response using OpenRouter.
        
        Args:
            prompt: User prompt
            system_prompt: Optional system prompt
            model: Optional specific model to use
        
        Returns:
            Generated text or None if failed
        """
        if not self.available:
            logger.warning("OpenRouter not available - API key not configured")
            return None
        
        model_to_use = model or self.default_model
        
        logger.info(
            "Calling OpenRouter API",
            extra={"payload": {"model": model_to_use, "prompt_length": len(prompt)}}
        )
        
        try:
            with OpenRouter(api_key=self.api_key) as client:
                messages = []
                
                if system_prompt:
                    messages.append({
                        "role": "system",
                        "content": system_prompt
                    })
                
                messages.append({
                    "role": "user",
                    "content": prompt
                })
                
                response = client.chat.send(
                    model=model_to_use,
                    messages=messages
                )
                
                result = response.choices[0].message.content
                
                logger.info(
                    "OpenRouter response received",
                    extra={"payload": {"response_length": len(result)}}
                )
                
                return result
        
        except Exception as e:
            logger.error(f"OpenRouter API call failed: {str(e)}")
            
            # Try fallback models
            if model_to_use == self.default_model:
                for fallback_model in self.fallback_models[1:]:
                    try:
                        logger.info(f"Trying fallback model: {fallback_model}")
                        with OpenRouter(api_key=self.api_key) as client:
                            messages = []
                            if system_prompt:
                                messages.append({"role": "system", "content": system_prompt})
                            messages.append({"role": "user", "content": prompt})
                            
                            response = client.chat.send(
                                model=fallback_model,
                                messages=messages
                            )
                            
                            return response.choices[0].message.content
                    except Exception as fallback_error:
                        logger.error(f"Fallback model {fallback_model} failed: {str(fallback_error)}")
                        continue
            
            return None
    
    def get_mock_response(self, prompt: str) -> str:
        """Return mock response when API is not available."""
        return f"""[MOCK RESPONSE - OpenRouter API not configured]

This is a simulated response for development purposes.
To enable real AI responses, set the OPENROUTER_API_KEY environment variable.

Your prompt: {prompt[:100]}...

In production, this would be generated by AI models via OpenRouter."""


# Global instance
openrouter_service = OpenRouterService()
